### PR TITLE
add procedures/referrals to report 

### PR DESCRIPTION
**Pull request by achen2401**
Adding Procedures (Not referrals)  and Referrals to the Treatment History section in the Report tab

Referrals are the ones that have concept code in `{
  '1009020',
  '1009077',
  '1009065',
  '1009019',
  '1009032'
}`

see screenshot of UI containing the changes:
Screenshot 2024-09-13 at 9 39 38 AM

### CODE REVIEW

**Comment by achen2401** [comment]
@mcjustin this should be ready for you to review.

**Comment by mcjustin** [comment]
> @mcjustin this should be ready for you to review.

Thanks @achen2401  - is that screenshot from your own dev system, or?

I think we should try this on the main dev system... you don't know of Patient's w/ these resources there, do you? 

If it looks good there then we'll switch staging (where we should have more FHIR data for testing this) to this branch.

**Comment by achen2401** [comment]
@mcjustin I posted sample FHIR Procedure data (from the json you gave me) to `Marcus Aurelius` on the [shared dev instance](https://dashboard.acc.dev.cosri.cirg.washington.edu/)

**Review by mcjustin — APPROVED** [review]
Thanks Amy - Looks good to me on the dev system

**Pull request merged**
